### PR TITLE
[#119] Fix Peewee connection

### PR DESCRIPTION
**Pull request by wdv4758h**

### CODE REVIEW

**Comment by wdv4758h** [comment]
Peewee 2.8.7

Backwards-incompatible changes:

* As of 9e76c99, an `OperationalError` is raised if the user calls `connect()`
  on an already-open Database object. Previously, the existing connection would
  remain open and a new connection would overwrite it, making it impossible to
  close the previous connection. If you find this is causing breakage in your
  application, you can switch the `connect()` call to `get_conn()` which will
  only open a connection if necessary. The error **is** indicative of a real
  issue, though, so audit your code for places where you may be opening a
  connection without closing it (module-scope operations, e.g.).

**Comment by wdv4758h** [comment]
Changing `connect()` to `get_conn()` will keep our code running as before.

**Comment by M157q** [comment]
Maybe we should bump to v0.9.7 for this?

**Comment by M157q** [comment]
wait
completer also used `db.connect()`

**Comment by wdv4758h** [comment]
It looks like the completer is still happy with `connect()`.

**Comment by wdv4758h** [comment]
I thinks it's because we are constructing the dictionary, which we are choosing, twice ?
(we have so many people sharing the `peewee.SqliteDatabase` object)

```sh
# the information is output from "__init__"
$ zdict
[DictBase] <peewee.SqliteDatabase object at 0x7f8996f78d30> moe
[DictBase] <peewee.SqliteDatabase object at 0x7f8996f78d30> moe-taiwanese
[DictBase] <peewee.SqliteDatabase object at 0x7f8996f78d30> yahoo
[DictBase] <peewee.SqliteDatabase object at 0x7f8996f78d30> jisho
[DictBase] <peewee.SqliteDatabase object at 0x7f8996f78d30> spanish
[DictBase] <peewee.SqliteDatabase object at 0x7f8996f78d30> urban
[DictCompleter] <peewee.SqliteDatabase object at 0x7f8996f78d30>
[DictBase] <peewee.SqliteDatabase object at 0x7f8996f78d30> yahoo
[zDict]: 
```

**Comment by wdv4758h** [comment]
In case we find another problem, I've modified the completer also.

**Pull request merged**
