### PR TITLE
[#148] Fix the bug when getting user home dir on Windows

### PR DESCRIPTION
**Pull request by M157q**
Use `os.path.expanduser` instead of using `os.path.join` directly,
since the formmer is better handled for Windows.

<https://docs.python.org/3/library/os.path.html#os.path.expanduser>

ref: GitHub issue #148

### CODE REVIEW

**Comment by M157q** [comment]
Should we use Appveyor to test if it works on Windows or we just bump version to 0.10.1 for this PR?

**Comment by iblis17** [comment]
Setting up Appveyor in the PR would be fine.

**Comment by M157q** [comment]
Sure. It may take some time.

**Comment by iblis17** [comment]
take your time.

**Comment by wdv4758h** [comment]
Finally, we have Windows user :P

**Comment by iblis17** [comment]
I'm also curious about the printing colour escape sequence is legit in Win's terminal or not.

**Comment by M157q** [comment]
Me, too. I don't think it will work. LOL

**Comment by M157q** [comment]
Some `appveyor.yml` examples:

+ https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
+ https://github.com/jakubroztocil/httpie/blob/master/appveyor.yml
+ https://packaging.python.org/guides/supporting-windows-using-appveyor/

**Comment by M157q** [comment]
I gave up.
There are too many problems to run `zdict` natively in `cmd.exe` on Windows.
For Windows user, just use Docker to run `zdict`.
Unless someone really want to implement this feature.

**Pull request closed without merging**
