### PR TITLE
ydict: new format

### PR DESCRIPTION
**Pull request by iblis17**
test cases:
- [x] `test`
- [x] `google`
- [x] `magic`
- [x] `hold on`
- [x] `fabor`
- [x] `hospitalize`, `hospitalized`
- [x] `doom`

feature:
- [x] verbose mode

### CODE REVIEW

**Comment by iblis17** [comment]
This PR is ready for review.

**Comment by M157q** [comment]
ref: #193

**Comment by M157q** [comment]
@iblis17 What happened to your commit messages? LOL

**Comment by iblis17** [comment]
Please squash while merging this branch. You can simply ignore those development steps.

**Pull request merged**
