### PR TITLE
Add verbose mode to Wiktionary

### PR DESCRIPTION
**Pull request by Aquakor**
### Description:

Previous version only showed the first definition provided by the API to the user.
This version does cover every part of speech , definitions and examples provided by the API :recycle:.
I'm really sad it turned out to be O(n^3) but can't think of a better solution right now.

There is also some code repetition in query and show function. I'm not sure if this is a problem. I tried to follow instructions provided in the dictionaries/template.py and that's why it turned out to be repetitive.

Sometimes there are repetitions in the API that are parsed to the Record, for example for a word 'box'. It is a good idea to fix this issue in the future.

### CODE REVIEW

**Comment by M157q** [comment]
I think you can modify the code to make this patch as verbose mode of wiktionary.
Don't just replace the previous version.

**Comment by Aquakor** [comment]
> I think you can modify the code to make this patch as verbose mode of wiktionary.
> Don't just replace the previous version.

I wasn't aware that verbose mode exists. I will do this.

**Comment by iblis17** [comment]
BTW, could you add a screenshot on README?

**Comment by Aquakor** [comment]
> BTW, could you add a screenshot on README?

Sure :+1:

**Pull request merged**
